<a href="https://colab.research.google.com/github/Ajitchan/Deep_learning/blob/main/2_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

In [2]:
# Load the Drive helper and mount your Google Drive as a drive in the virtual machine
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/Deep_learning')

In [4]:
os.getcwd()
os.listdir()

['1 - Neural Network For Handwritten Digits Classification .ipynb',
 '2 - Gradient_Descent.ipynb']

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Big_data/Data/insurance.csv')
df['smoker'] = df.smoker.replace(to_replace=['no', 'yes'], value=[0, 1])

In [8]:
df

age     sex   bmi  children  smoker     region  expenses
0      19  female  27.9         0       1  southwest  16884.92
1      18    male  33.8         1       0  southeast   1725.55
2      28    male  33.0         3       0  southeast   4449.46
3      33    male  22.7         0       0  northwest  21984.47
4      32    male  28.9         0       0  northwest   3866.86
...   ...     ...   ...       ...     ...        ...       ...
1333   50    male  31.0         3       0  northwest  10600.55
1334   18  female  31.9         0       0  northeast   2205.98
1335   18  female  36.9         0       0  southeast   1629.83
1336   21  female  25.8         0       0  southwest   2007.95
1337   61  female  29.1         0       1  northwest  29141.36

[1338 rows x 7 columns]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[['age','bmi']], df.smoker, test_size = 0.1, random_state = 25)

In [16]:
X_test

age   bmi
748    47  36.0
633    40  22.7
651    53  39.6
411    44  20.2
502    51  23.2
...   ...   ...
479    23  32.6
671    29  31.2
333    56  28.8
162    54  39.6
1000   30  23.0

[134 rows x 2 columns]

In [19]:
# Scalling

X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100
X_train_scaled['bmi'] = X_train_scaled['bmi'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100
X_test_scaled['bmi'] = X_test_scaled['bmi'] / 100

print(len(X_test_scaled))
print(len(y_test))

print(len(X_train_scaled))
print(len(y_train))

age    bmi
748   0.47  0.360
633   0.40  0.227
651   0.53  0.396
411   0.44  0.202
502   0.51  0.232
...    ...    ...
479   0.23  0.326
671   0.29  0.312
333   0.56  0.288
162   0.54  0.396
1000  0.30  0.230

[134 rows x 2 columns]

# Part 2 - Modelling

In [32]:
model = keras.Sequential([
                          keras.layers.Dense(1, input_shape = (2,), activation='sigmoid', kernel_initializer='ones', bias_initializer= 'zeros')
]) # kernel_initializer is a weight value for inputs

model.compile( optimizer='adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.fit(X_train_scaled, y_train, epochs= 5000)

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.4834 - accuracy: 0.8119
Epoch 2502/5000
38/38 [==============================] - 0s 3ms/step - loss: 0.4742 - accuracy: 0.8185
Epoch 2503/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.4891 - accuracy: 0.8077
Epoch 2504/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.4982 - accuracy: 0.8012
Epoch 2505/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.4855 - accuracy: 0.8112
Epoch 2506/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.4858 - accuracy: 0.8108
Epoch 2507/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.5005 - accuracy: 0.7991
Epoch 2508/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.4882 - accuracy: 0.8076
Epoch 2509/5000
38/38 [==============================] - 0s 2ms/step - loss: 0.5056 - accuracy: 0.7952
Epoch 2510/5000
38/38 

In [33]:
model.evaluate(X_test_scaled,y_test)

5/5 [==============================] - 0s 2ms/step - loss: 0.6218 - accuracy: 0.7164


[0.6217513084411621, 0.7164179086685181]

In [34]:
X_test_scaled

age    bmi
748   0.47  0.360
633   0.40  0.227
651   0.53  0.396
411   0.44  0.202
502   0.51  0.232
...    ...    ...
479   0.23  0.326
671   0.29  0.312
333   0.56  0.288
162   0.54  0.396
1000  0.30  0.230

[134 rows x 2 columns]

In [35]:
y_test

748     0
633     0
651     0
411     1
502     1
       ..
479     0
671     0
333     0
162     0
1000    1
Name: smoker, Length: 134, dtype: int64

In [36]:
model.predict(X_test_scaled)

array([[0.19578531],
       [0.18416977],
       [0.1955095 ],
       [0.17780763],
       [0.17602086],
       [0.2130934 ],
       [0.19356   ],
       [0.18216631],
       [0.18672225],
       [0.21690679],
       [0.20027035],
       [0.18691814],
       [0.19626862],
       [0.18060455],
       [0.19544426],
       [0.17961955],
       [0.18746647],
       [0.18720335],
       [0.21813333],
       [0.20686188],
       [0.18990394],
       [0.19585419],
       [0.1913577 ],
       [0.18620518],
       [0.1785135 ],
       [0.20262828],
       [0.18729594],
       [0.18512657],
       [0.21199727],
       [0.19735032],
       [0.19763577],
       [0.21896076],
       [0.18687007],
       [0.19849041],
       [0.19755852],
       [0.17642736],
       [0.17302552],
       [0.20986176],
       [0.18760002],
       [0.1866889 ],
       [0.17950112],
       [0.16582471],
       [0.214571  ],
       [0.18752572],
       [0.18829855],
       [0.21575105],
       [0.18990028],
       [0.170

In [38]:
# To get final weight values
coef, intercept = model.get_weights()
coef, intercept
# weight 1 is -0.54050183, weight 2 is 0.85214955 and bias is -1.4655855

(array([[-0.54050183],
        [ 0.85214955]], dtype=float32), array([-1.4655855], dtype=float32))

# Part 3 - Gradient Descent

In [39]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [40]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [52]:
# Using gradient_descent function to manually find weight 1, weight 2 and bias
def gradient_descent (age, bmi, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * bmi + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)
        
        # derivaties
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(bmi),(y_predicted-y_true)) 
        bias_d = np.mean(y_predicted-y_true)

        # Backwark error propogation
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias


In [55]:
gradient_descent(X_train_scaled['age'],X_train_scaled['bmi'], y_train, 5000, 0.4933 )

Streaming output truncated to the last 5000 lines.
Epoch:0, w1:0.905206554814282, w2:0.9275958503303365, bias:-0.2352263817325786, loss:0.9682484560042273
Epoch:1, w1:0.8236716744605801, w2:0.8655785828860665, bias:-0.4365648390641006, loss:0.8389752774883428
Epoch:2, w1:0.7542423804942767, w2:0.8129962464275736, bias:-0.6071845101730109, loss:0.7446223953248506
Epoch:3, w1:0.6953433030622944, w2:0.7685899192428717, bias:-0.7512266709050781, loss:0.6769190328617949
Epoch:4, w1:0.6453391818555193, w2:0.7310712956115417, bias:-0.8729059333361691, loss:0.6285999350798297
Epoch:5, w1:0.6027370865079296, w2:0.6992735697994203, bias:-0.9760270244507879, loss:0.5940259395824689
Epoch:6, w1:0.5662615374551021, w2:0.672204820632498, bias:-1.0638175488139934, loss:0.5691076598915294
Epoch:7, w1:0.5348590233608491, w2:0.649048392658359, bias:-1.13893094624, loss:0.5509779461208101
Epoch:8, w1:0.50767274228995, w2:0.6291415488850222, bias:-1.203518329961261, loss:0.5376526024593001
Epoch:9, w1:0.4

(-0.5370004849494038, 0.7848580075641569, -1.4445957597308925)

In [56]:
coef, intercept

(array([[-0.54050183],
        [ 0.85214955]], dtype=float32), array([-1.4655855], dtype=float32))